### ISSUE TITLE
Install pip dependencies in China

### ISSUE THREAD

**Issue by JunnanZ** [QuantEcon/lecture-intro.zh-cn#108]
When building the `quantecon` environment by running
```
conda env create -f environment.yml
```
users in China might get stuck at
```
Installing pip dependencies...
```

Running the command with a VPN doesn't have this problem.

**Comment by JunnanZ** [comment]
I managed to use a PyPI mirror based at Tsinghua university to successfully install the dependencies without using a VPN. You can do this by adding one line in `environment.yml`:

```diff
1 file changed, 1 insertion(+)
environment.yml | 1 +

modified   environment.yml
@@ -18,6 +18,7 @@ dependencies:
     - sphinxcontrib-youtube==1.1.0
     - sphinx-togglebutton==0.3.1
     - sphinx_reredirects==0.1.3
+    - --index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
     # Sandpit Requirements
     # - PuLP
     # - cvxpy
```

Further instructions can be found at https://mirrors.tuna.tsinghua.edu.cn/help/pypi/ (in Chinese).

You can also set `conda` to download from a mirror at Tsinghua, which can make the process much faster for users in China. See https://mirror.tuna.tsinghua.edu.cn/help/anaconda/.

**Comment by mmcky** [comment]
thanks @JunnanZ this is great. I will create an environment-cn.yml for RAs in china.
