### ISSUE TITLE
problems in running "jb build lectures"

### ISSUE THREAD

**Issue by katicyan** [QuantEcon/lecture-intro.zh-cn#113]
Here is some logs for errors, it may caused by internet connecting. Luckily, after session in 11/15, I tried again and these problems aroused again but it finally succed!  So I think it can be solved by retry them.
[french_rev.err.log](https://github.com/user-attachments/files/17775068/french_rev.err.log)
[inequality.err.log](https://github.com/user-attachments/files/17775089/inequality.err.log)
![image](https://github.com/user-attachments/assets/6a38e423-a4c2-45f0-ab53-6d93d226f8c8)
![image](https://github.com/user-attachments/assets/f073cfed-bda8-4615-b6fc-ea2f424b52f9)

**Comment by mmcky** [comment]
thanks for the feedback and registering this issue @katicyan
