### ISSUE TITLE
Difference in .md file between English version and Chinese version

### ISSUE THREAD

**Issue by katicyan** [QuantEcon/lecture-intro.zh-cn#116]
While reading on this website and I found there is no source .md file. 'sir_model.md' is the source file and I didn't find it in the folder cloned from Chinese repo. And seems there is other difference in .md file between English and Chinese version. 
![image](https://github.com/user-attachments/assets/8e52f75f-5ef2-4c17-b4b6-14f46856d66d)
![image](https://github.com/user-attachments/assets/2bb880a6-cbb3-43da-bcb4-84988262b156)
![image](https://github.com/user-attachments/assets/a533220f-af32-4db2-b3e2-86ee8bf07b2b)

**Comment by mmcky** [comment]
@katicyan -- the `sir_model.md` lecture belongs to our Intermediate Quantitative Economics Lecture Series. 

The only series that has been translated to Chinese so far is the 

intro.quantecon.org

lecture series. 

The next series on the list for translation is

python-programming.quantecon.org.

**Comment by katicyan** [comment]
ok, I got it.
