### ISSUE TITLE
[intro_demand_supply] Bug in matplotlib

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-intro.zh-cn#30]
Currently the matplotlib figures are not displaying Chinese characters correctly

<img width="816" alt="Screenshot 2024-09-18 at 10 54 28 am" src="https://github.com/user-attachments/assets/836837ef-6422-4321-b85c-da1bbf0bf745">

@longye-tian can you apply @HumphreyYang fix to the top code block to see if it fixes this issue https://github.com/QuantEcon/lecture-intro.zh-cn/issues/5

**Comment by longye-tian** [comment]
Hi Matt @mmcky ,

Thanks for point this out. I'll try to fix this.

Best,
Longye

**Comment by HumphreyYang** [comment]
In addition to adding the code in the code cells, on the Linux machine/server, we need to add the Chinese font by adding the font `SimHei.ttf` to the mpl directory 
(i.e.,

/home/humphrey/anaconda3/envs/quantecon/lib/python3.1/site-packages/matplotlib/mpl-data/fonts/ttf

)

or we can https://matplotlib.org/stable/gallery/text_labels_and_annotations/font_file.html

I managed to make it work on my Linux server : )

(see more at https://stackoverflow.com/questions/40290004/how-can-i-configure-matplotlib-to-be-able-to-read-fonts-from-a-local-path)

**Comment by mmcky** [comment]
thanks @HumphreyYang I have seen this also -- perhaps we can use system wide fonts and passing a fonts property to the legend?

https://stackoverflow.com/questions/39630928/how-to-plot-a-figure-with-chinese-characters-in-label

**Comment by HumphreyYang** [comment]
> thanks @HumphreyYang I have seen this also -- perhaps we can use system wide fonts and passing a fonts property to the legend?
> 
> 
> 
> https://stackoverflow.com/questions/39630928/how-to-plot-a-figure-with-chinese-characters-in-label

Hi @mmcky,

I tried this too, but I still need to add the ttf file into the mpl folder to make it work : (

**Comment by HumphreyYang** [comment]
This issue is solved by adding

```
import matplotlib as mpl
mpl.font_manager.fontManager.addfont(r"../lectures/_static/SourceHanSerifSC-SemiBold.otf")
plt.rcParams['font.family'] = ['Source Han Serif SC']
```

to imports at the beginning of the lecture.

See #35.

**Comment by mmcky** [comment]
Great -- that's what I thought. Cheers.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I found some PRs have not yet been updated to this solution. Maybe we should keep an eye on this?

**Comment by mmcky** [comment]
https://github.com/QuantEcon/lecture-intro.zh-cn/issues/61
