### ISSUE TITLE
Potential Issues in AI Translation

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/lecture-intro.zh-cn#5]
- [x] `matplotlib` requires an update in the font library to show Chinese:
```
from matplotlib import font_manager

fontP = font_manager.FontProperties()
fontP.set_family('SimHei')
fontP.set_size(14)
```
- [x] code cells are sometimes broken into two and we need to delete the code block AI created in the middle to run the code.  (I have updated the code to take out code cells separately, but it has limitation if we have code cell with 4000+ characters)

**Comment by HumphreyYang** [comment]
> * [ ]  `matplotlib` requires an update in the font library to show Chinese:
> 
> ```
> from matplotlib import font_manager
> 
> fontP = font_manager.FontProperties()
> fontP.set_family('SimHei')
> fontP.set_size(14)
> ```
> 
> * [x]  code cells are sometimes broken into two and we need to delete the code block AI created in the middle to run the code.  (I have updated the code to take out code cells separately, but it has limitation if we have code cell with 4000+ characters)

In addition to this, on Linux machine/server, we need to add the Chinese font missing by adding the font `SimHei.ttf` to the mpl directory 
(i.e.,

/home/humphrey/anaconda3/envs/quantecon/lib/python3.1/site-packages/matplotlib/mpl-data/fonts/ttf

)

**Comment by mmcky** [comment]
@HumphreyYang do I need to add these fonts still?

**Comment by HumphreyYang** [comment]
No not anymore. We can use the new solution without modifying the infrastructure side:

https://github.com/QuantEcon/lecture-intro.zh-cn/issues/30#issuecomment-2367889578

**Comment by mmcky** [comment]
Closing as this as the correct solution has now been documented 

https://github.com/QuantEcon/lecture-intro.zh-cn/wiki/Matplotlib-Figure-Translation-Tools
