### ISSUE TITLE
Translation Lecture Ownership -- Initial Translation

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-intro.zh-cn#6]
This is a list of files to help us coordinate who will translate which files. Please feel free to take ownership of individual files (but edit this top level box and put your @ name behind the file to help coordinate with the team. 

**Introduction** (@SylviaZhaooo)
- [x]  about

**Economic Data** (@HumphreyYang)
- [x]  long_run_growth
- [x]  business_cycle
- [x]  inflation_history
- [x]  french_rev 
- [x]  inequality

**Foundations** (@longye-tian)
- [x]  intro_supply_demand
- [x]  linear_equations
- [x]  complex_and_trig
- [x]  geom_series

**Linear Dynamics: Finite Horizons** (@longye-tian)
- [x]  pv
- [x]  cons_smooth
- [x]  equalizing_difference
- [x]  cagan_ree
- [x]  cagan_adaptive

**Linear Dynamics: Infinite Horizons** (@longye-tian)
- [x]  eigen_I
- [x]  greek_square 

**Probability and Distributions** (@SylviaZhaooo)
- [x]  prob_dist
- [x]  lln_clt
- [x]  monte_carlo
- [x]  heavy_tails
- [x]  schelling

**Nonlinear Dynamics** (@longye-tian)
- [x]  scalar_dynam
- [x]  solow
- [x]  cobweb
- [x]  olg
- [x]  commod_price

**Monetary-Fiscal Policy Interactions** (@SylviaZhaooo)
- [x]  money_inflation
- [x]  unpleasant
- [x]  money_inflation_nonlinear
- [x]  laffer_adaptive

**Stochastic Dynamics** (@HumphreyYang)
- [x]  ar1_processes
- [x]  markov_chains_I
- [x]  markov_chains_II
- [x]  time_series_with_matrices

**Optimization** (@longye-tian)
- [x]  lp_intro
- [x]  short_path

**Modeling in Higher Dimensions** (@longye-tian)
- [x]  eigen_II
- [x]  input_output
- [x]  lake_model
- [x]  networks

**Markets and Competitive Equilibrium** (@SylviaZhaooo)

- [x]  supply_demand_multiple_goods
- [x]  supply_demand_heterogeneity

**Estimation** (@SylviaZhaooo)
- [x]  simple_linear_regression
- [x]  mle

**Other**
- [x]  troubleshooting
- [x]  zreferences
- [x]  status

**Comment by mmcky** [comment]
thanks @longye-tian @SylviaZhaooo @HumphreyYang -- we are close to closing this issue. 

@SylviaZhaooo or @longye-tian would you have any time to handle the `other` section of translations. They are pretty short pages.

**Comment by SylviaZhaooo** [comment]
Hi @mmcky,

I can handle the `other` section and finish it this week.

**Comment by mmcky** [comment]
Thanks everyone. 

I think the only one remaining is `scalar_dynam` 

- [ ] `scalar_dynam`

**Comment by mmcky** [comment]
thanks @HumphreyYang @SylviaZhaooo and @longye-tian
