### ISSUE TITLE
[Style] Line break after each sentence

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/lecture-intro.zh-cn#74]
Some lectures on the list do not currently have line breaks for sentences (i.e. https://quantecon.github.io/lecture-intro.zh-cn/networks.html)

**Comment by HumphreyYang** [comment]
Hi @longye-tian, Would you mind running through this issue : )?

**Comment by HumphreyYang** [comment]
Mostly fixed in #72

**Comment by mmcky** [comment]
thanks for your help on this @HumphreyYang I think we can close this now. 

We can do a QuantEcon style check at some point.
