### ISSUE TITLE
Translation Glossary

### ISSUE THREAD

**Issue by longye-tian** [QuantEcon/lecture-intro.zh-cn#79]
Hey team @HumphreyYang @SylviaZhaooo @mmcky,

I've added a glossary of terms from our lectures to the wiki, including name translations.

Feel free to add any new ones you spot!

Cheers,
Longye

**Comment by HumphreyYang** [comment]
Thanks so much @longye-tian!

**Comment by mmcky** [comment]
@longye-tian thanks for the glossary. That's a great resource for us.

**Comment by mmcky** [comment]
Glossary is located in

https://github.com/QuantEcon/lecture-intro.zh-cn/wiki/Glossary
