### ISSUE TITLE
Link Checker Failures: Broken and Redirected URLs

### ISSUE THREAD

**Issue by SylviaZhaooo** [QuantEcon/lecture-intro.zh-cn#80]
Hi Team @mmcky @HumphreyYang @longye-tian,

After translating the last three lectures, all three PRs show checker failure for the same reason.

The link checker flagged several broken and redirected links in the documentation that need to be addressed.

Issues:

Broken Links (404 or 403 Errors):
Example: https://networks.quantecon.org/%EF%BC%8C%E4%BD%86%E6%9C%AC%E8%AE%B2%E5%BA%A7%E7%9A%84%E6%B0%B4%E5%B9%B3%E6%9B%B4%E4%B8%BA%E5%85%A5%E9%97%A8%E3%80%82 (404)
Example: https://unctad.org/publication/commodities-and-development-report-2019 (403)

Redirected Links:
Example: http://www.mathsisfun.com/algebra/matrix-multiplying.html -> https://www.mathsisfun.com/algebra/matrix-multiplying.html
Example: https://doi.org/10.1007/978-1-4614-3284-5 -> https://link.springer.com/book/10.1007/978-1-4614-3284-5

Best,
Sylvia

**Comment by HumphreyYang** [comment]
Many thanks @SylviaZhaooo. I can fix this issue in the main directly and then merge the main into your PRs.

**Comment by HumphreyYang** [comment]
This is now fixed: https://github.com/QuantEcon/lecture-intro.zh-cn/actions/runs/11197361915/job/31127235114?pr=78

**Comment by SylviaZhaooo** [comment]
Many thanks @HumphreyYang.
